---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
    ignore:
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore sigs.k8s.io/cluster-api as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api/*"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
    groups:
      gomod:
        update-types:
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
    groups:
      actions:
        update-types:
          - "patch"
          - "minor"
