// +build !ignore_autogenerated_core_v1alpha3

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen-v0.22.2. DO NOT EDIT.

package v1alpha3

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	v1beta1 "sigs.k8s.io/cluster-api-provider-digitalocean/api/v1beta1"
	errors "sigs.k8s.io/cluster-api/errors"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BuildTagParams)(nil), (*v1beta1.BuildTagParams)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_BuildTagParams_To_v1beta1_BuildTagParams(a.(*BuildTagParams), b.(*v1beta1.BuildTagParams), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.BuildTagParams)(nil), (*BuildTagParams)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_BuildTagParams_To_v1alpha3_BuildTagParams(a.(*v1beta1.BuildTagParams), b.(*BuildTagParams), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOCluster)(nil), (*v1beta1.DOCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOCluster_To_v1beta1_DOCluster(a.(*DOCluster), b.(*v1beta1.DOCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOCluster)(nil), (*DOCluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOCluster_To_v1alpha3_DOCluster(a.(*v1beta1.DOCluster), b.(*DOCluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOClusterList)(nil), (*v1beta1.DOClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOClusterList_To_v1beta1_DOClusterList(a.(*DOClusterList), b.(*v1beta1.DOClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOClusterList)(nil), (*DOClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOClusterList_To_v1alpha3_DOClusterList(a.(*v1beta1.DOClusterList), b.(*DOClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOClusterSpec)(nil), (*v1beta1.DOClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOClusterSpec_To_v1beta1_DOClusterSpec(a.(*DOClusterSpec), b.(*v1beta1.DOClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOClusterSpec)(nil), (*DOClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOClusterSpec_To_v1alpha3_DOClusterSpec(a.(*v1beta1.DOClusterSpec), b.(*DOClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOClusterStatus)(nil), (*v1beta1.DOClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOClusterStatus_To_v1beta1_DOClusterStatus(a.(*DOClusterStatus), b.(*v1beta1.DOClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOClusterStatus)(nil), (*DOClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOClusterStatus_To_v1alpha3_DOClusterStatus(a.(*v1beta1.DOClusterStatus), b.(*DOClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOControlPlaneDNS)(nil), (*v1beta1.DOControlPlaneDNS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOControlPlaneDNS_To_v1beta1_DOControlPlaneDNS(a.(*DOControlPlaneDNS), b.(*v1beta1.DOControlPlaneDNS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOControlPlaneDNS)(nil), (*DOControlPlaneDNS)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOControlPlaneDNS_To_v1alpha3_DOControlPlaneDNS(a.(*v1beta1.DOControlPlaneDNS), b.(*DOControlPlaneDNS), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOLoadBalancer)(nil), (*v1beta1.DOLoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOLoadBalancer_To_v1beta1_DOLoadBalancer(a.(*DOLoadBalancer), b.(*v1beta1.DOLoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOLoadBalancer)(nil), (*DOLoadBalancer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOLoadBalancer_To_v1alpha3_DOLoadBalancer(a.(*v1beta1.DOLoadBalancer), b.(*DOLoadBalancer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOLoadBalancerHealthCheck)(nil), (*v1beta1.DOLoadBalancerHealthCheck)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOLoadBalancerHealthCheck_To_v1beta1_DOLoadBalancerHealthCheck(a.(*DOLoadBalancerHealthCheck), b.(*v1beta1.DOLoadBalancerHealthCheck), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOLoadBalancerHealthCheck)(nil), (*DOLoadBalancerHealthCheck)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOLoadBalancerHealthCheck_To_v1alpha3_DOLoadBalancerHealthCheck(a.(*v1beta1.DOLoadBalancerHealthCheck), b.(*DOLoadBalancerHealthCheck), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOMachine)(nil), (*v1beta1.DOMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOMachine_To_v1beta1_DOMachine(a.(*DOMachine), b.(*v1beta1.DOMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOMachine)(nil), (*DOMachine)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOMachine_To_v1alpha3_DOMachine(a.(*v1beta1.DOMachine), b.(*DOMachine), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOMachineList)(nil), (*v1beta1.DOMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOMachineList_To_v1beta1_DOMachineList(a.(*DOMachineList), b.(*v1beta1.DOMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOMachineList)(nil), (*DOMachineList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOMachineList_To_v1alpha3_DOMachineList(a.(*v1beta1.DOMachineList), b.(*DOMachineList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOMachineSpec)(nil), (*v1beta1.DOMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOMachineSpec_To_v1beta1_DOMachineSpec(a.(*DOMachineSpec), b.(*v1beta1.DOMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOMachineSpec)(nil), (*DOMachineSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOMachineSpec_To_v1alpha3_DOMachineSpec(a.(*v1beta1.DOMachineSpec), b.(*DOMachineSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOMachineStatus)(nil), (*v1beta1.DOMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOMachineStatus_To_v1beta1_DOMachineStatus(a.(*DOMachineStatus), b.(*v1beta1.DOMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOMachineStatus)(nil), (*DOMachineStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOMachineStatus_To_v1alpha3_DOMachineStatus(a.(*v1beta1.DOMachineStatus), b.(*DOMachineStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOMachineTemplate)(nil), (*v1beta1.DOMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOMachineTemplate_To_v1beta1_DOMachineTemplate(a.(*DOMachineTemplate), b.(*v1beta1.DOMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOMachineTemplate)(nil), (*DOMachineTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOMachineTemplate_To_v1alpha3_DOMachineTemplate(a.(*v1beta1.DOMachineTemplate), b.(*DOMachineTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOMachineTemplateList)(nil), (*v1beta1.DOMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOMachineTemplateList_To_v1beta1_DOMachineTemplateList(a.(*DOMachineTemplateList), b.(*v1beta1.DOMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOMachineTemplateList)(nil), (*DOMachineTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOMachineTemplateList_To_v1alpha3_DOMachineTemplateList(a.(*v1beta1.DOMachineTemplateList), b.(*DOMachineTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOMachineTemplateResource)(nil), (*v1beta1.DOMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOMachineTemplateResource_To_v1beta1_DOMachineTemplateResource(a.(*DOMachineTemplateResource), b.(*v1beta1.DOMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOMachineTemplateResource)(nil), (*DOMachineTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOMachineTemplateResource_To_v1alpha3_DOMachineTemplateResource(a.(*v1beta1.DOMachineTemplateResource), b.(*DOMachineTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOMachineTemplateSpec)(nil), (*v1beta1.DOMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOMachineTemplateSpec_To_v1beta1_DOMachineTemplateSpec(a.(*DOMachineTemplateSpec), b.(*v1beta1.DOMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOMachineTemplateSpec)(nil), (*DOMachineTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOMachineTemplateSpec_To_v1alpha3_DOMachineTemplateSpec(a.(*v1beta1.DOMachineTemplateSpec), b.(*DOMachineTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DONetwork)(nil), (*v1beta1.DONetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DONetwork_To_v1beta1_DONetwork(a.(*DONetwork), b.(*v1beta1.DONetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DONetwork)(nil), (*DONetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DONetwork_To_v1alpha3_DONetwork(a.(*v1beta1.DONetwork), b.(*DONetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DONetworkResource)(nil), (*v1beta1.DONetworkResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DONetworkResource_To_v1beta1_DONetworkResource(a.(*DONetworkResource), b.(*v1beta1.DONetworkResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DONetworkResource)(nil), (*DONetworkResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DONetworkResource_To_v1alpha3_DONetworkResource(a.(*v1beta1.DONetworkResource), b.(*DONetworkResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOResourceReference)(nil), (*v1beta1.DOResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOResourceReference_To_v1beta1_DOResourceReference(a.(*DOResourceReference), b.(*v1beta1.DOResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOResourceReference)(nil), (*DOResourceReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOResourceReference_To_v1alpha3_DOResourceReference(a.(*v1beta1.DOResourceReference), b.(*DOResourceReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DOVPC)(nil), (*v1beta1.DOVPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DOVPC_To_v1beta1_DOVPC(a.(*DOVPC), b.(*v1beta1.DOVPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DOVPC)(nil), (*DOVPC)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DOVPC_To_v1alpha3_DOVPC(a.(*v1beta1.DOVPC), b.(*DOVPC), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataDisk)(nil), (*v1beta1.DataDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha3_DataDisk_To_v1beta1_DataDisk(a.(*DataDisk), b.(*v1beta1.DataDisk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta1.DataDisk)(nil), (*DataDisk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DataDisk_To_v1alpha3_DataDisk(a.(*v1beta1.DataDisk), b.(*DataDisk), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha3_BuildTagParams_To_v1beta1_BuildTagParams(in *BuildTagParams, out *v1beta1.BuildTagParams, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.ClusterUID = in.ClusterUID
	out.Name = in.Name
	out.Role = in.Role
	out.Additional = *(*v1beta1.Tags)(unsafe.Pointer(&in.Additional))
	return nil
}

// Convert_v1alpha3_BuildTagParams_To_v1beta1_BuildTagParams is an autogenerated conversion function.
func Convert_v1alpha3_BuildTagParams_To_v1beta1_BuildTagParams(in *BuildTagParams, out *v1beta1.BuildTagParams, s conversion.Scope) error {
	return autoConvert_v1alpha3_BuildTagParams_To_v1beta1_BuildTagParams(in, out, s)
}

func autoConvert_v1beta1_BuildTagParams_To_v1alpha3_BuildTagParams(in *v1beta1.BuildTagParams, out *BuildTagParams, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	out.ClusterUID = in.ClusterUID
	out.Name = in.Name
	out.Role = in.Role
	out.Additional = *(*Tags)(unsafe.Pointer(&in.Additional))
	return nil
}

// Convert_v1beta1_BuildTagParams_To_v1alpha3_BuildTagParams is an autogenerated conversion function.
func Convert_v1beta1_BuildTagParams_To_v1alpha3_BuildTagParams(in *v1beta1.BuildTagParams, out *BuildTagParams, s conversion.Scope) error {
	return autoConvert_v1beta1_BuildTagParams_To_v1alpha3_BuildTagParams(in, out, s)
}

func autoConvert_v1alpha3_DOCluster_To_v1beta1_DOCluster(in *DOCluster, out *v1beta1.DOCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_DOClusterSpec_To_v1beta1_DOClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_DOClusterStatus_To_v1beta1_DOClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DOCluster_To_v1beta1_DOCluster is an autogenerated conversion function.
func Convert_v1alpha3_DOCluster_To_v1beta1_DOCluster(in *DOCluster, out *v1beta1.DOCluster, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOCluster_To_v1beta1_DOCluster(in, out, s)
}

func autoConvert_v1beta1_DOCluster_To_v1alpha3_DOCluster(in *v1beta1.DOCluster, out *DOCluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_DOClusterSpec_To_v1alpha3_DOClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DOClusterStatus_To_v1alpha3_DOClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DOCluster_To_v1alpha3_DOCluster is an autogenerated conversion function.
func Convert_v1beta1_DOCluster_To_v1alpha3_DOCluster(in *v1beta1.DOCluster, out *DOCluster, s conversion.Scope) error {
	return autoConvert_v1beta1_DOCluster_To_v1alpha3_DOCluster(in, out, s)
}

func autoConvert_v1alpha3_DOClusterList_To_v1beta1_DOClusterList(in *DOClusterList, out *v1beta1.DOClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.DOCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_DOClusterList_To_v1beta1_DOClusterList is an autogenerated conversion function.
func Convert_v1alpha3_DOClusterList_To_v1beta1_DOClusterList(in *DOClusterList, out *v1beta1.DOClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOClusterList_To_v1beta1_DOClusterList(in, out, s)
}

func autoConvert_v1beta1_DOClusterList_To_v1alpha3_DOClusterList(in *v1beta1.DOClusterList, out *DOClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DOCluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_DOClusterList_To_v1alpha3_DOClusterList is an autogenerated conversion function.
func Convert_v1beta1_DOClusterList_To_v1alpha3_DOClusterList(in *v1beta1.DOClusterList, out *DOClusterList, s conversion.Scope) error {
	return autoConvert_v1beta1_DOClusterList_To_v1alpha3_DOClusterList(in, out, s)
}

func autoConvert_v1alpha3_DOClusterSpec_To_v1beta1_DOClusterSpec(in *DOClusterSpec, out *v1beta1.DOClusterSpec, s conversion.Scope) error {
	out.Region = in.Region
	if err := Convert_v1alpha3_DONetwork_To_v1beta1_DONetwork(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.ControlPlaneDNS = (*v1beta1.DOControlPlaneDNS)(unsafe.Pointer(in.ControlPlaneDNS))
	return nil
}

// Convert_v1alpha3_DOClusterSpec_To_v1beta1_DOClusterSpec is an autogenerated conversion function.
func Convert_v1alpha3_DOClusterSpec_To_v1beta1_DOClusterSpec(in *DOClusterSpec, out *v1beta1.DOClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOClusterSpec_To_v1beta1_DOClusterSpec(in, out, s)
}

func autoConvert_v1beta1_DOClusterSpec_To_v1alpha3_DOClusterSpec(in *v1beta1.DOClusterSpec, out *DOClusterSpec, s conversion.Scope) error {
	out.Region = in.Region
	if err := Convert_v1beta1_DONetwork_To_v1alpha3_DONetwork(&in.Network, &out.Network, s); err != nil {
		return err
	}
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	out.ControlPlaneDNS = (*DOControlPlaneDNS)(unsafe.Pointer(in.ControlPlaneDNS))
	return nil
}

// Convert_v1beta1_DOClusterSpec_To_v1alpha3_DOClusterSpec is an autogenerated conversion function.
func Convert_v1beta1_DOClusterSpec_To_v1alpha3_DOClusterSpec(in *v1beta1.DOClusterSpec, out *DOClusterSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_DOClusterSpec_To_v1alpha3_DOClusterSpec(in, out, s)
}

func autoConvert_v1alpha3_DOClusterStatus_To_v1beta1_DOClusterStatus(in *DOClusterStatus, out *v1beta1.DOClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.ControlPlaneDNSRecordReady = in.ControlPlaneDNSRecordReady
	if err := Convert_v1alpha3_DONetworkResource_To_v1beta1_DONetworkResource(&in.Network, &out.Network, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DOClusterStatus_To_v1beta1_DOClusterStatus is an autogenerated conversion function.
func Convert_v1alpha3_DOClusterStatus_To_v1beta1_DOClusterStatus(in *DOClusterStatus, out *v1beta1.DOClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOClusterStatus_To_v1beta1_DOClusterStatus(in, out, s)
}

func autoConvert_v1beta1_DOClusterStatus_To_v1alpha3_DOClusterStatus(in *v1beta1.DOClusterStatus, out *DOClusterStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.ControlPlaneDNSRecordReady = in.ControlPlaneDNSRecordReady
	if err := Convert_v1beta1_DONetworkResource_To_v1alpha3_DONetworkResource(&in.Network, &out.Network, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DOClusterStatus_To_v1alpha3_DOClusterStatus is an autogenerated conversion function.
func Convert_v1beta1_DOClusterStatus_To_v1alpha3_DOClusterStatus(in *v1beta1.DOClusterStatus, out *DOClusterStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_DOClusterStatus_To_v1alpha3_DOClusterStatus(in, out, s)
}

func autoConvert_v1alpha3_DOControlPlaneDNS_To_v1beta1_DOControlPlaneDNS(in *DOControlPlaneDNS, out *v1beta1.DOControlPlaneDNS, s conversion.Scope) error {
	out.Domain = in.Domain
	out.Name = in.Name
	return nil
}

// Convert_v1alpha3_DOControlPlaneDNS_To_v1beta1_DOControlPlaneDNS is an autogenerated conversion function.
func Convert_v1alpha3_DOControlPlaneDNS_To_v1beta1_DOControlPlaneDNS(in *DOControlPlaneDNS, out *v1beta1.DOControlPlaneDNS, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOControlPlaneDNS_To_v1beta1_DOControlPlaneDNS(in, out, s)
}

func autoConvert_v1beta1_DOControlPlaneDNS_To_v1alpha3_DOControlPlaneDNS(in *v1beta1.DOControlPlaneDNS, out *DOControlPlaneDNS, s conversion.Scope) error {
	out.Domain = in.Domain
	out.Name = in.Name
	return nil
}

// Convert_v1beta1_DOControlPlaneDNS_To_v1alpha3_DOControlPlaneDNS is an autogenerated conversion function.
func Convert_v1beta1_DOControlPlaneDNS_To_v1alpha3_DOControlPlaneDNS(in *v1beta1.DOControlPlaneDNS, out *DOControlPlaneDNS, s conversion.Scope) error {
	return autoConvert_v1beta1_DOControlPlaneDNS_To_v1alpha3_DOControlPlaneDNS(in, out, s)
}

func autoConvert_v1alpha3_DOLoadBalancer_To_v1beta1_DOLoadBalancer(in *DOLoadBalancer, out *v1beta1.DOLoadBalancer, s conversion.Scope) error {
	out.Port = in.Port
	out.Algorithm = in.Algorithm
	if err := Convert_v1alpha3_DOLoadBalancerHealthCheck_To_v1beta1_DOLoadBalancerHealthCheck(&in.HealthCheck, &out.HealthCheck, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DOLoadBalancer_To_v1beta1_DOLoadBalancer is an autogenerated conversion function.
func Convert_v1alpha3_DOLoadBalancer_To_v1beta1_DOLoadBalancer(in *DOLoadBalancer, out *v1beta1.DOLoadBalancer, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOLoadBalancer_To_v1beta1_DOLoadBalancer(in, out, s)
}

func autoConvert_v1beta1_DOLoadBalancer_To_v1alpha3_DOLoadBalancer(in *v1beta1.DOLoadBalancer, out *DOLoadBalancer, s conversion.Scope) error {
	out.Port = in.Port
	out.Algorithm = in.Algorithm
	if err := Convert_v1beta1_DOLoadBalancerHealthCheck_To_v1alpha3_DOLoadBalancerHealthCheck(&in.HealthCheck, &out.HealthCheck, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DOLoadBalancer_To_v1alpha3_DOLoadBalancer is an autogenerated conversion function.
func Convert_v1beta1_DOLoadBalancer_To_v1alpha3_DOLoadBalancer(in *v1beta1.DOLoadBalancer, out *DOLoadBalancer, s conversion.Scope) error {
	return autoConvert_v1beta1_DOLoadBalancer_To_v1alpha3_DOLoadBalancer(in, out, s)
}

func autoConvert_v1alpha3_DOLoadBalancerHealthCheck_To_v1beta1_DOLoadBalancerHealthCheck(in *DOLoadBalancerHealthCheck, out *v1beta1.DOLoadBalancerHealthCheck, s conversion.Scope) error {
	out.Interval = in.Interval
	out.Timeout = in.Timeout
	out.UnhealthyThreshold = in.UnhealthyThreshold
	out.HealthyThreshold = in.HealthyThreshold
	return nil
}

// Convert_v1alpha3_DOLoadBalancerHealthCheck_To_v1beta1_DOLoadBalancerHealthCheck is an autogenerated conversion function.
func Convert_v1alpha3_DOLoadBalancerHealthCheck_To_v1beta1_DOLoadBalancerHealthCheck(in *DOLoadBalancerHealthCheck, out *v1beta1.DOLoadBalancerHealthCheck, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOLoadBalancerHealthCheck_To_v1beta1_DOLoadBalancerHealthCheck(in, out, s)
}

func autoConvert_v1beta1_DOLoadBalancerHealthCheck_To_v1alpha3_DOLoadBalancerHealthCheck(in *v1beta1.DOLoadBalancerHealthCheck, out *DOLoadBalancerHealthCheck, s conversion.Scope) error {
	out.Interval = in.Interval
	out.Timeout = in.Timeout
	out.UnhealthyThreshold = in.UnhealthyThreshold
	out.HealthyThreshold = in.HealthyThreshold
	return nil
}

// Convert_v1beta1_DOLoadBalancerHealthCheck_To_v1alpha3_DOLoadBalancerHealthCheck is an autogenerated conversion function.
func Convert_v1beta1_DOLoadBalancerHealthCheck_To_v1alpha3_DOLoadBalancerHealthCheck(in *v1beta1.DOLoadBalancerHealthCheck, out *DOLoadBalancerHealthCheck, s conversion.Scope) error {
	return autoConvert_v1beta1_DOLoadBalancerHealthCheck_To_v1alpha3_DOLoadBalancerHealthCheck(in, out, s)
}

func autoConvert_v1alpha3_DOMachine_To_v1beta1_DOMachine(in *DOMachine, out *v1beta1.DOMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_DOMachineSpec_To_v1beta1_DOMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_DOMachineStatus_To_v1beta1_DOMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DOMachine_To_v1beta1_DOMachine is an autogenerated conversion function.
func Convert_v1alpha3_DOMachine_To_v1beta1_DOMachine(in *DOMachine, out *v1beta1.DOMachine, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOMachine_To_v1beta1_DOMachine(in, out, s)
}

func autoConvert_v1beta1_DOMachine_To_v1alpha3_DOMachine(in *v1beta1.DOMachine, out *DOMachine, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_DOMachineSpec_To_v1alpha3_DOMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DOMachineStatus_To_v1alpha3_DOMachineStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DOMachine_To_v1alpha3_DOMachine is an autogenerated conversion function.
func Convert_v1beta1_DOMachine_To_v1alpha3_DOMachine(in *v1beta1.DOMachine, out *DOMachine, s conversion.Scope) error {
	return autoConvert_v1beta1_DOMachine_To_v1alpha3_DOMachine(in, out, s)
}

func autoConvert_v1alpha3_DOMachineList_To_v1beta1_DOMachineList(in *DOMachineList, out *v1beta1.DOMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.DOMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_DOMachineList_To_v1beta1_DOMachineList is an autogenerated conversion function.
func Convert_v1alpha3_DOMachineList_To_v1beta1_DOMachineList(in *DOMachineList, out *v1beta1.DOMachineList, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOMachineList_To_v1beta1_DOMachineList(in, out, s)
}

func autoConvert_v1beta1_DOMachineList_To_v1alpha3_DOMachineList(in *v1beta1.DOMachineList, out *DOMachineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DOMachine)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_DOMachineList_To_v1alpha3_DOMachineList is an autogenerated conversion function.
func Convert_v1beta1_DOMachineList_To_v1alpha3_DOMachineList(in *v1beta1.DOMachineList, out *DOMachineList, s conversion.Scope) error {
	return autoConvert_v1beta1_DOMachineList_To_v1alpha3_DOMachineList(in, out, s)
}

func autoConvert_v1alpha3_DOMachineSpec_To_v1beta1_DOMachineSpec(in *DOMachineSpec, out *v1beta1.DOMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.Size = in.Size
	out.Image = in.Image
	out.DataDisks = *(*[]v1beta1.DataDisk)(unsafe.Pointer(&in.DataDisks))
	out.SSHKeys = *(*[]intstr.IntOrString)(unsafe.Pointer(&in.SSHKeys))
	out.AdditionalTags = *(*v1beta1.Tags)(unsafe.Pointer(&in.AdditionalTags))
	return nil
}

// Convert_v1alpha3_DOMachineSpec_To_v1beta1_DOMachineSpec is an autogenerated conversion function.
func Convert_v1alpha3_DOMachineSpec_To_v1beta1_DOMachineSpec(in *DOMachineSpec, out *v1beta1.DOMachineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOMachineSpec_To_v1beta1_DOMachineSpec(in, out, s)
}

func autoConvert_v1beta1_DOMachineSpec_To_v1alpha3_DOMachineSpec(in *v1beta1.DOMachineSpec, out *DOMachineSpec, s conversion.Scope) error {
	out.ProviderID = (*string)(unsafe.Pointer(in.ProviderID))
	out.Size = in.Size
	out.Image = in.Image
	out.DataDisks = *(*[]DataDisk)(unsafe.Pointer(&in.DataDisks))
	out.SSHKeys = *(*[]intstr.IntOrString)(unsafe.Pointer(&in.SSHKeys))
	out.AdditionalTags = *(*Tags)(unsafe.Pointer(&in.AdditionalTags))
	return nil
}

// Convert_v1beta1_DOMachineSpec_To_v1alpha3_DOMachineSpec is an autogenerated conversion function.
func Convert_v1beta1_DOMachineSpec_To_v1alpha3_DOMachineSpec(in *v1beta1.DOMachineSpec, out *DOMachineSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_DOMachineSpec_To_v1alpha3_DOMachineSpec(in, out, s)
}

func autoConvert_v1alpha3_DOMachineStatus_To_v1beta1_DOMachineStatus(in *DOMachineStatus, out *v1beta1.DOMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = (*v1beta1.DOResourceStatus)(unsafe.Pointer(in.InstanceStatus))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1alpha3_DOMachineStatus_To_v1beta1_DOMachineStatus is an autogenerated conversion function.
func Convert_v1alpha3_DOMachineStatus_To_v1beta1_DOMachineStatus(in *DOMachineStatus, out *v1beta1.DOMachineStatus, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOMachineStatus_To_v1beta1_DOMachineStatus(in, out, s)
}

func autoConvert_v1beta1_DOMachineStatus_To_v1alpha3_DOMachineStatus(in *v1beta1.DOMachineStatus, out *DOMachineStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.Addresses = *(*[]v1.NodeAddress)(unsafe.Pointer(&in.Addresses))
	out.InstanceStatus = (*DOResourceStatus)(unsafe.Pointer(in.InstanceStatus))
	out.FailureReason = (*errors.MachineStatusError)(unsafe.Pointer(in.FailureReason))
	out.FailureMessage = (*string)(unsafe.Pointer(in.FailureMessage))
	return nil
}

// Convert_v1beta1_DOMachineStatus_To_v1alpha3_DOMachineStatus is an autogenerated conversion function.
func Convert_v1beta1_DOMachineStatus_To_v1alpha3_DOMachineStatus(in *v1beta1.DOMachineStatus, out *DOMachineStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_DOMachineStatus_To_v1alpha3_DOMachineStatus(in, out, s)
}

func autoConvert_v1alpha3_DOMachineTemplate_To_v1beta1_DOMachineTemplate(in *DOMachineTemplate, out *v1beta1.DOMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha3_DOMachineTemplateSpec_To_v1beta1_DOMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DOMachineTemplate_To_v1beta1_DOMachineTemplate is an autogenerated conversion function.
func Convert_v1alpha3_DOMachineTemplate_To_v1beta1_DOMachineTemplate(in *DOMachineTemplate, out *v1beta1.DOMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOMachineTemplate_To_v1beta1_DOMachineTemplate(in, out, s)
}

func autoConvert_v1beta1_DOMachineTemplate_To_v1alpha3_DOMachineTemplate(in *v1beta1.DOMachineTemplate, out *DOMachineTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_DOMachineTemplateSpec_To_v1alpha3_DOMachineTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DOMachineTemplate_To_v1alpha3_DOMachineTemplate is an autogenerated conversion function.
func Convert_v1beta1_DOMachineTemplate_To_v1alpha3_DOMachineTemplate(in *v1beta1.DOMachineTemplate, out *DOMachineTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_DOMachineTemplate_To_v1alpha3_DOMachineTemplate(in, out, s)
}

func autoConvert_v1alpha3_DOMachineTemplateList_To_v1beta1_DOMachineTemplateList(in *DOMachineTemplateList, out *v1beta1.DOMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta1.DOMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha3_DOMachineTemplateList_To_v1beta1_DOMachineTemplateList is an autogenerated conversion function.
func Convert_v1alpha3_DOMachineTemplateList_To_v1beta1_DOMachineTemplateList(in *DOMachineTemplateList, out *v1beta1.DOMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOMachineTemplateList_To_v1beta1_DOMachineTemplateList(in, out, s)
}

func autoConvert_v1beta1_DOMachineTemplateList_To_v1alpha3_DOMachineTemplateList(in *v1beta1.DOMachineTemplateList, out *DOMachineTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DOMachineTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_DOMachineTemplateList_To_v1alpha3_DOMachineTemplateList is an autogenerated conversion function.
func Convert_v1beta1_DOMachineTemplateList_To_v1alpha3_DOMachineTemplateList(in *v1beta1.DOMachineTemplateList, out *DOMachineTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_DOMachineTemplateList_To_v1alpha3_DOMachineTemplateList(in, out, s)
}

func autoConvert_v1alpha3_DOMachineTemplateResource_To_v1beta1_DOMachineTemplateResource(in *DOMachineTemplateResource, out *v1beta1.DOMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_DOMachineSpec_To_v1beta1_DOMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DOMachineTemplateResource_To_v1beta1_DOMachineTemplateResource is an autogenerated conversion function.
func Convert_v1alpha3_DOMachineTemplateResource_To_v1beta1_DOMachineTemplateResource(in *DOMachineTemplateResource, out *v1beta1.DOMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOMachineTemplateResource_To_v1beta1_DOMachineTemplateResource(in, out, s)
}

func autoConvert_v1beta1_DOMachineTemplateResource_To_v1alpha3_DOMachineTemplateResource(in *v1beta1.DOMachineTemplateResource, out *DOMachineTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_DOMachineSpec_To_v1alpha3_DOMachineSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DOMachineTemplateResource_To_v1alpha3_DOMachineTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_DOMachineTemplateResource_To_v1alpha3_DOMachineTemplateResource(in *v1beta1.DOMachineTemplateResource, out *DOMachineTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_DOMachineTemplateResource_To_v1alpha3_DOMachineTemplateResource(in, out, s)
}

func autoConvert_v1alpha3_DOMachineTemplateSpec_To_v1beta1_DOMachineTemplateSpec(in *DOMachineTemplateSpec, out *v1beta1.DOMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1alpha3_DOMachineTemplateResource_To_v1beta1_DOMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DOMachineTemplateSpec_To_v1beta1_DOMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha3_DOMachineTemplateSpec_To_v1beta1_DOMachineTemplateSpec(in *DOMachineTemplateSpec, out *v1beta1.DOMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOMachineTemplateSpec_To_v1beta1_DOMachineTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_DOMachineTemplateSpec_To_v1alpha3_DOMachineTemplateSpec(in *v1beta1.DOMachineTemplateSpec, out *DOMachineTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_DOMachineTemplateResource_To_v1alpha3_DOMachineTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DOMachineTemplateSpec_To_v1alpha3_DOMachineTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_DOMachineTemplateSpec_To_v1alpha3_DOMachineTemplateSpec(in *v1beta1.DOMachineTemplateSpec, out *DOMachineTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_DOMachineTemplateSpec_To_v1alpha3_DOMachineTemplateSpec(in, out, s)
}

func autoConvert_v1alpha3_DONetwork_To_v1beta1_DONetwork(in *DONetwork, out *v1beta1.DONetwork, s conversion.Scope) error {
	if err := Convert_v1alpha3_DOLoadBalancer_To_v1beta1_DOLoadBalancer(&in.APIServerLoadbalancers, &out.APIServerLoadbalancers, s); err != nil {
		return err
	}
	if err := Convert_v1alpha3_DOVPC_To_v1beta1_DOVPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DONetwork_To_v1beta1_DONetwork is an autogenerated conversion function.
func Convert_v1alpha3_DONetwork_To_v1beta1_DONetwork(in *DONetwork, out *v1beta1.DONetwork, s conversion.Scope) error {
	return autoConvert_v1alpha3_DONetwork_To_v1beta1_DONetwork(in, out, s)
}

func autoConvert_v1beta1_DONetwork_To_v1alpha3_DONetwork(in *v1beta1.DONetwork, out *DONetwork, s conversion.Scope) error {
	if err := Convert_v1beta1_DOLoadBalancer_To_v1alpha3_DOLoadBalancer(&in.APIServerLoadbalancers, &out.APIServerLoadbalancers, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DOVPC_To_v1alpha3_DOVPC(&in.VPC, &out.VPC, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DONetwork_To_v1alpha3_DONetwork is an autogenerated conversion function.
func Convert_v1beta1_DONetwork_To_v1alpha3_DONetwork(in *v1beta1.DONetwork, out *DONetwork, s conversion.Scope) error {
	return autoConvert_v1beta1_DONetwork_To_v1alpha3_DONetwork(in, out, s)
}

func autoConvert_v1alpha3_DONetworkResource_To_v1beta1_DONetworkResource(in *DONetworkResource, out *v1beta1.DONetworkResource, s conversion.Scope) error {
	if err := Convert_v1alpha3_DOResourceReference_To_v1beta1_DOResourceReference(&in.APIServerLoadbalancersRef, &out.APIServerLoadbalancersRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha3_DONetworkResource_To_v1beta1_DONetworkResource is an autogenerated conversion function.
func Convert_v1alpha3_DONetworkResource_To_v1beta1_DONetworkResource(in *DONetworkResource, out *v1beta1.DONetworkResource, s conversion.Scope) error {
	return autoConvert_v1alpha3_DONetworkResource_To_v1beta1_DONetworkResource(in, out, s)
}

func autoConvert_v1beta1_DONetworkResource_To_v1alpha3_DONetworkResource(in *v1beta1.DONetworkResource, out *DONetworkResource, s conversion.Scope) error {
	if err := Convert_v1beta1_DOResourceReference_To_v1alpha3_DOResourceReference(&in.APIServerLoadbalancersRef, &out.APIServerLoadbalancersRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_DONetworkResource_To_v1alpha3_DONetworkResource is an autogenerated conversion function.
func Convert_v1beta1_DONetworkResource_To_v1alpha3_DONetworkResource(in *v1beta1.DONetworkResource, out *DONetworkResource, s conversion.Scope) error {
	return autoConvert_v1beta1_DONetworkResource_To_v1alpha3_DONetworkResource(in, out, s)
}

func autoConvert_v1alpha3_DOResourceReference_To_v1beta1_DOResourceReference(in *DOResourceReference, out *v1beta1.DOResourceReference, s conversion.Scope) error {
	out.ResourceID = in.ResourceID
	out.ResourceStatus = v1beta1.DOResourceStatus(in.ResourceStatus)
	return nil
}

// Convert_v1alpha3_DOResourceReference_To_v1beta1_DOResourceReference is an autogenerated conversion function.
func Convert_v1alpha3_DOResourceReference_To_v1beta1_DOResourceReference(in *DOResourceReference, out *v1beta1.DOResourceReference, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOResourceReference_To_v1beta1_DOResourceReference(in, out, s)
}

func autoConvert_v1beta1_DOResourceReference_To_v1alpha3_DOResourceReference(in *v1beta1.DOResourceReference, out *DOResourceReference, s conversion.Scope) error {
	out.ResourceID = in.ResourceID
	out.ResourceStatus = DOResourceStatus(in.ResourceStatus)
	return nil
}

// Convert_v1beta1_DOResourceReference_To_v1alpha3_DOResourceReference is an autogenerated conversion function.
func Convert_v1beta1_DOResourceReference_To_v1alpha3_DOResourceReference(in *v1beta1.DOResourceReference, out *DOResourceReference, s conversion.Scope) error {
	return autoConvert_v1beta1_DOResourceReference_To_v1alpha3_DOResourceReference(in, out, s)
}

func autoConvert_v1alpha3_DOVPC_To_v1beta1_DOVPC(in *DOVPC, out *v1beta1.DOVPC, s conversion.Scope) error {
	out.VPCUUID = in.VPCUUID
	return nil
}

// Convert_v1alpha3_DOVPC_To_v1beta1_DOVPC is an autogenerated conversion function.
func Convert_v1alpha3_DOVPC_To_v1beta1_DOVPC(in *DOVPC, out *v1beta1.DOVPC, s conversion.Scope) error {
	return autoConvert_v1alpha3_DOVPC_To_v1beta1_DOVPC(in, out, s)
}

func autoConvert_v1beta1_DOVPC_To_v1alpha3_DOVPC(in *v1beta1.DOVPC, out *DOVPC, s conversion.Scope) error {
	out.VPCUUID = in.VPCUUID
	return nil
}

// Convert_v1beta1_DOVPC_To_v1alpha3_DOVPC is an autogenerated conversion function.
func Convert_v1beta1_DOVPC_To_v1alpha3_DOVPC(in *v1beta1.DOVPC, out *DOVPC, s conversion.Scope) error {
	return autoConvert_v1beta1_DOVPC_To_v1alpha3_DOVPC(in, out, s)
}

func autoConvert_v1alpha3_DataDisk_To_v1beta1_DataDisk(in *DataDisk, out *v1beta1.DataDisk, s conversion.Scope) error {
	out.NameSuffix = in.NameSuffix
	out.DiskSizeGB = in.DiskSizeGB
	out.FilesystemType = in.FilesystemType
	out.FilesystemLabel = in.FilesystemLabel
	return nil
}

// Convert_v1alpha3_DataDisk_To_v1beta1_DataDisk is an autogenerated conversion function.
func Convert_v1alpha3_DataDisk_To_v1beta1_DataDisk(in *DataDisk, out *v1beta1.DataDisk, s conversion.Scope) error {
	return autoConvert_v1alpha3_DataDisk_To_v1beta1_DataDisk(in, out, s)
}

func autoConvert_v1beta1_DataDisk_To_v1alpha3_DataDisk(in *v1beta1.DataDisk, out *DataDisk, s conversion.Scope) error {
	out.NameSuffix = in.NameSuffix
	out.DiskSizeGB = in.DiskSizeGB
	out.FilesystemType = in.FilesystemType
	out.FilesystemLabel = in.FilesystemLabel
	return nil
}

// Convert_v1beta1_DataDisk_To_v1alpha3_DataDisk is an autogenerated conversion function.
func Convert_v1beta1_DataDisk_To_v1alpha3_DataDisk(in *v1beta1.DataDisk, out *DataDisk, s conversion.Scope) error {
	return autoConvert_v1beta1_DataDisk_To_v1alpha3_DataDisk(in, out, s)
}
